---
  - name: "My first playbook"
    hosts: localhost

    tasks:

      - name: "test reachability"
        ping:

      - name: "install stress"
        apt: name=stress update_cache=yes state=latest
    